apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: djk-s
build:
  artifacts:
  - image: django-webapp
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/secrets.yaml
    - k8s/django/deployment.yaml
    - k8s/django/service.yaml
    - k8s/postgres/deployment.yaml
    - k8s/postgres/service.yaml
    - k8s/postgres/volume.yaml
    - k8s/postgres/volume_claim.yaml
portForward:
- resourceType: deployment
  resourceName: django
  port: 8000
