apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-container
  template:
    metadata:
      labels:
        app: django-container
    spec:
      containers:
        - name: django
          imagePullPolicy: IfNotPresent
          image: django-webapp:latest
          command: ["./manage.py", "runserver", "0.0.0.0:8000"]
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: app-secret
          volumeMounts:
            - name: postgres-volume-mount
              mountPath: /var/lib/busybox
      volumes:
        - name: postgres-volume-mount
          persistentVolumeClaim:
            claimName: postgres-pvc
