apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: django
          imagePullPolicy: IfNotPresent
          image: django-webapp:latest
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SECRET_KEY
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_PASSWORD
          command: ['python', 'manage.py', 'migrate']
      restartPolicy: Never
  backoffLimit: 5
